### ISSUE TITLE
Date resets to default value on Save

### ISSUE THREAD

**Issue by ashygk** [surveyjs/survey-library#1259]
### Are you requesting a feature, reporting a bug or asking a question?

bug / question

### What is the current behavior?

When my survey json has a matrix dynamic with date(custom datepicker) being one of the column and set the default value to current date using onMatrixCellCreated event.
`  private onMatrixCellCreated(survey, options) {
    if (options.columnName.startsWith('Date')) {
      options.rowValue[options.columnName] = new Date().toLocaleDateString();
    }
  }`

When I add a matrix row and remove the date and save, the survey data still shows current date, while it should be empty / null.

survey json : `{
            pages: [
                {
                    name: "page1",
                    elements: [
                        {
                            type: "matrixdynamic",
                            name: "ComplexMedicalNeeds",
                            titleLocation: "hidden",
                            columns: [
                                {
                                    name: "Date",
                                    cellType: "datepicker",
                                    dateFormat: "mm/dd/yy",
                                    config: {
                                        showOn: "button",
                                        buttonImage:
                                        "assets/icons/date.svg",
                                        buttonImageOnly: true,
                                        buttonText: "Select date",
                                        maxDate: "+0D"
                                    },
                                    inputType: "date"
                                },
                                {
                                    name: "Narrative",
                                    cellType: "comment",
                                    maxLength: 2000,
                                    validators: [
                                        {
                                            type: "text",
                                            allowDigits: true,
                                            minLength: 0,
                                            maxLength: 2000
                                        }
                                    ]
                                },
                                {
                                    name: "Actions",
                                    visibleIf: "1 = 2"
                                }
                            ],
                            cellType: "text",
                            rowCount: 0,
                            addRowLocation: "top",
                            addRowText: "ADD COMPLEX NEED  +",
                            removeRowText: " ",
                            confirmDelete: true,
                            confirmDeleteText: "Are you sure you want to delete medical/nursing needs record?"
                        }
                    ]
                }
            ],
            showTitle: false,
            showQuestionNumbers: "off",
            questionErrorLocation: "bottom"
        }`

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
Are you using the `datepicker` from custom widgets repo (https://github.com/surveyjs/widgets/blob/master/src/bootstrapdatepicker.js)?

**Comment by ashygk** [comment]
@tsv2013 Yes. I'm using jquery ui datepicker

**Comment by ashygk** [comment]
@tsv2013 any update on this please?

**Comment by tsv2013** [comment]
@ashygk Thanks for pinging me. Sorry no updates for now.

**Comment by dmitrykurmanov** [comment]
@ashygk I will check it ASAP.

**Comment by dmitrykurmanov** [comment]
@ashygk the problem in datepicker itself, please check the issue on stackoverflow: https://stackoverflow.com/questions/9435086/how-do-i-clear-reset-the-selected-dates-on-the-jquery-ui-datepicker-calendar

I've fixed it via the commit: https://github.com/surveyjs/widgets/commit/11dba510b59a7edd19f0776ce4d97c08a519b5f5

Here an example: https://plnkr.co/edit/dtUoEOSugVq0rvlqsHJa?p=preview with the last widget build.

The fix will be available in the next minor update.

**Comment by ashygk** [comment]
@andrewtelnov Thanks for re-opening the issue. The issue still persists when onMatrixCellCreated event is used. Could you please verify by adding the below code snippet in the plunkr and verify. Thanks.

`private onMatrixCellCreated(survey, options) { if (options.columnName.startsWith('Date')) { options.rowValue[options.columnName] = new Date().toLocaleDateString(); } }`

**Comment by andrewtelnov** [comment]
@ashygk I have updated the [plunker example](https://plnkr.co/edit/KQlKdnZ3gJAGazfFbJte?p=preview) accordingly.

Thank you,
Andrew

**Comment by tsv2013** [comment]
@ashygk I've fixed the issue, but you need to use `options.cellQuestion.value` instead of the `options.rowValue[options.columnName]`:

```JS
survey.onMatrixCellCreated.add(function(survey, options) {
    if (options.columnName.startsWith('Date')) {
        options.cellQuestion.value = new Date().toLocaleDateString();
        //options.row.setValue(options.columnName, new Date().toLocaleDateString()); // or this notation
    }
});
```

**Comment by ashygk** [comment]
@tsv2013 When will this be released? I believe you have every Tuesday deployments.

**Comment by ashygk** [comment]
Please find the images below: 
1. I added a new row, with date defaulting to todays date i.e. 21st Aug.
![1](https://user-images.githubusercontent.com/36975459/44415491-2c9b6a80-a536-11e8-8370-3b12995c0a83.PNG)
2.  I changed the date to 1st Aug and filled the comment field.
![2](https://user-images.githubusercontent.com/36975459/44415527-49d03900-a536-11e8-80a3-041feae093c8.PNG)
3. I added a new row again.
![2 5](https://user-images.githubusercontent.com/36975459/44415828-fc080080-a536-11e8-82c2-312a8da0c370.PNG)
4. Changed the date to 2nd Aug. Now the first row date is changed to 2nd Aug.
![3](https://user-images.githubusercontent.com/36975459/44415894-1f32b000-a537-11e8-8e91-c2c815e35c75.PNG)
5. Similarly, added another row.
![4](https://user-images.githubusercontent.com/36975459/44415961-4f7a4e80-a537-11e8-9352-05d041e4e4c1.PNG)
6. Now I changed the date of new row to 3rd Aug, the date of first row is changed to 3rd Aug.
![5](https://user-images.githubusercontent.com/36975459/44416016-73d62b00-a537-11e8-8d84-8254d35db095.PNG)
But, upon saved, the following are being saved. The first row date has recently applied date and remaining rows have todays date.
![6](https://user-images.githubusercontent.com/36975459/44416206-ee9f4600-a537-11e8-9f8c-6198dd046c23.PNG)

**Comment by tsv2013** [comment]
@ashygk The 1.0.39 had been released yesterday. Just've checked your steps on this plunker (https://plnkr.co/edit/Nex6abAN9Skm00wunOo8?p=preview) with the 1.0.39. It works ok for me. Could you check it?

**Comment by ashygk** [comment]
It works fine in plunkr but not in our application

**Comment by tsv2013** [comment]
@ashygk If it doesn't work in your application, we need a working sample to reproduce the issue on our side. Otherwise we will not be able to fix it.

**Comment by tsv2013** [comment]
@ashygk Is it another issue? Is this issue related to another date selecting control? Can you give me steps, how to reproduce it?
The plunker is - https://plnkr.co/edit/Nex6abAN9Skm00wunOo8?p=preview

**Comment by ashygk** [comment]
We are using surveyjs date. Please see the survey json below.
Json: `{
  pages: [
    {
      name: "page1",
      elements: [
        {
          type: "matrixdynamic",
          name: "ComplexMedicalNeeds",
          titleLocation: "hidden",
          columns: [
            {
              name: "Date",
              cellType: "text",
              inputType: "date"
            },
            {
              name: "Narrative",
              cellType: "comment",
              maxLength: 2000,
              validators: [
                {
                  type: "text",
                  allowDigits: true,
                  minLength: 0,
                  maxLength: 2000
                }
              ]
            },
            { name: "Actions", visibleIf: "1 = 2" }
          ],
          cellType: "text",
          rowCount: 0,
          addRowLocation: "top",
          addRowText: "ADD COMPLEX NEED +",
          removeRowText: " ",
          confirmDelete: true,
          confirmDeleteText:
            "Are you sure you want to delete medical/nursing needs record?"
        }
      ]
    }
  ],
  showTitle: false,
  showQuestionNumbers: "off",
  questionErrorLocation: "bottom"
};
`

`private onMatrixCellCreated(survey, options) { if (options.columnName.startsWith('Date')) { options.rowValue[options.columnName] = new Date().toLocaleDateString(); } }`

**Comment by tsv2013** [comment]
You need to use 
```JS
options.cellQuestion.value = new Date().toLocaleDateString();
```

**Comment by ashygk** [comment]
It doesn't work when it is surveyjs date.(Please see the modified json). Works when custom datepicker is used

**Comment by tsv2013** [comment]
I've reproduced the issue - value is not displayed in matrix but exists in survey results.

**Comment by ashygk** [comment]
@tsv2013 Yes. Which shouldn't be the case. It has to display the current date in the matrix too. Is it happening because of the placeholder mm/dd/yyyy?. Is there a chance to remove that placeholder for date?  I didn't find a property for it while building the survey.

**Comment by tsv2013** [comment]
According to the https://stackoverflow.com/questions/12346381/set-date-in-input-type-date
I've updated the plunk - https://plnkr.co/edit/7uBdREvDUwa4V52yqfNk?p=preview
Is this solution ok for you?

**Comment by tsv2013** [comment]
As for your question - now there is no format options for the built-in date selector. We'll discuss it with the team.
