### ISSUE TITLE
Survey viewer fails to render if the survey editor has been opened during the same session.

### ISSUE THREAD

**Issue by csgchristian** [surveyjs/survey-library#1698]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting a bug

### What is the current behavior?

If the SurveyJS editor has been opened in the current angular session, the SurveyJS survey viewer will not work.

### What is the expected behavior?

The SurveyJS survey viewer should work.

### How would you reproduce the current behavior (if this is a bug)?

https://next.plnkr.co/edit/h0AatAXjD48CyWHr?preview

Click 'Open Survey' and then 'Open Editor' - Take note how both are properly rendered.

Refresh, click 'Open Editor', scroll down and click 'Open Survey' - Take note how the Survey will never render.

* surveyjs platform (angular or react or jquery or knockout or vue): Angular
* surveyjs version: 1.0.88

**Comment by csgchristian** [comment]
Note: The issue does not persist when building on surveyjs version 1.0.68, this is a new bug.

**Comment by joseph-newton** [comment]
We've encountered this in 1.0.83 too.

**Comment by joseph-newton** [comment]
This is the same issue as [Survey not able to rerender after Survey Creator has rendered #23](https://github.com/surveyjs/surveyjs_angular_cli/issues/23).

The [workaround](https://github.com/surveyjs/surveyjs_angular_cli/issues/23#issuecomment-490557659) in that thread works for me...
```
    ...

    console.log("init survey");

    function surveyFix() {
      var surveyContentParentNode = null;
      var surveyContentNode = document.getElementById("survey-content");
      var isRenderedBefore = !!surveyContentNode;

      if (isRenderedBefore) {
        surveyContentParentNode = surveyContentNode.parentNode;
        surveyContentParentNode.parentNode.removeChild(surveyContentParentNode);
      }
    }
    surveyFix();

    surveyModel.render("surveyElement");
```

**Comment by tsv2013** [comment]
It's a bug. We're working on the fix.

Temporary workaround is to use KnockoutJS of v < 3.5.0, e.g. 3.4.2

**Comment by tsv2013** [comment]
We've fixed the issue. Fix will be available in the nearest update, most likely next tuesday.

**Comment by nitishjeebun** [comment]
Hello,

This issue is back again, the rendering fails when attempting to render a second time in Angular.

Thanks to check this again.

**Comment by tsv2013** [comment]
Here is the plunker from the TS with the survey libraries v1.7.4 - https://plnkr.co/edit/NaSnTAfkQiaKScf9

It works ok for me. How we can reproduce the issue?
