### ISSUE TITLE
"iif" function breaking if falseValue is set to empty string

### ISSUE THREAD

**Issue by starg09** [surveyjs/survey-library#1942]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
Using the "iif" function in a nested way, inside an expression block, the whole expression seems to break if the falseValue is set to "" (an empty string), even if there's some valid text before it

### What is the expected behavior?

The expression working and, if the condition isn't met, for that section of the expression to just be a blank area (no spaces used).

### How would you reproduce the current behavior (if this is a bug)?

Using the expression attached below works, but a soon as the final `"X"` is replaced with `""` the whole thing breaks. No matter what the final stored value will be empty.

If you just remove the whole falseValue part, it works but when condition isn't met a "0" is added, which I presume is just the default value for the option.

#### Provide the test code and the tested page URL (if applicable)

Test code

```
{quest_type}  + 
iif(
    {quest_type} = "MSS",
    "[" + 
    iif(
        {meguca_type} = "Unlimited (Natural 1-3 Stars)",
        {ms_unlimited_13},
        iif(
            {meguca_type} = "Unlimited (Natural 4 Stars)",
            {ms_unlimited_4},
            iif(
                {meguca_type} = "Event/Time Limited (Gacha/Fate Weave)",
                {ms_limited_gacha},
                iif(
                    {meguca_type} = "Event/Time Limited (Shop/Welfare)",
                    {ms_limited_shop},
                    "??????"
                )
            )
        )
    ) +
    "]",
    "X"
)

```

**Comment by tsv2013** [comment]
Reproduced with the following JSON:
```JSON
{
 "completedHtml": "Thank you for choosing {animal}!",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "question3"
    },
    {
     "type": "radiogroup",
     "name": "question1",
     "choices": [
      {
       "value": "item1",
       "text": "item1"
      },
      "item2",
      "item3"
     ]
    },
    {
     "type": "expression",
     "name": "question2",
     "expression": "{question3} + iif( {question1} = \"item2\", \"[\" + {question3} + \"]\", \"x\")",
     "commentText": "Other (describe)"
    }
   ]
  }
 ]
}
```

**Comment by andrewtelnov** [comment]
@starg09 I have added unit tests and fixed the issue. The problem was with contact two strings, where one string is undefined/null variable.
The bug is fixed in the commit above. It will be included into the next minor update that we will release next week, hopefully in 2019 :)

Thank

**Comment by tobia** [comment]
@andrewtelnov  This bug is not entirely solved, at least in 1.9.34 and 1.9.35 (but probably before that too.)

In my tests, the following expression does not work when **initially** setting the answers, using either `survey.setValue(...)` or `survey.data = ...` before rendering the survey:
```
iif({someField} anyof ['A', 'B'], 'some text', '')
```
I made it work by changing the second argument to a non-empty string:
```
iif({someField} anyof ['A', 'B'], 'some text', ' ')
                                               ^^^
```
Note: the one with an empty string still works when **manually** entering the answer for `someField`, but not when setting the data programmatically before the first render.

Could you please check and reopen the issue? Thanks
