### ISSUE TITLE
matrixdynamic does not remove empty rows when data is reset

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#1958]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?

matrixdynamic does not remove empty rows when data is reset programmatically 

### What is the expected behavior?

UI should reflect the data

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/4vpml3dTess7M0g1CrDy?p=preview

**Comment by andrewtelnov** [comment]
@masciugo We will take a look.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@masciugo The issue has been fixed.

Thank you,
Andrew

**Comment by masciugo** [comment]
Thank you @andrewtelnov but it still does not work in the following scenario:

https://plnkr.co/edit/Ln7jjBX4tkoWar5TXA7E?p=preview

if you try to alter the survey content and then reset to the initial data by pressing the button, brand new matrixdynamic rows are still shown while all other values are correctly reset

**Comment by andrewtelnov** [comment]
@masciugo Added a new case into unit test and fix it.

Thank you,
Andrew
