### ISSUE TITLE
Triggers referencing question names with dot not working

### ISSUE THREAD

**Issue by dasboe** [surveyjs/survey-library#2420]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?

When using a dot in a question name triggers do not work

### What is the expected behavior?

Triggers work with dots in question name

### How would you reproduce the current behavior (if this is a bug)?

Create a question with a dot in question name. Use a trigger with this question name.

#### Provide the test code and the tested page URL (if applicable)

Test code

```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "dropdown",
     "name": "question1",
     "choices": [
      "item1",
      "item2",
      "item3",
      "item4"
     ]
    },
    {
     "type": "text",
     "name": "question.name2"
    }
   ]
  }
 ],
 "triggers": [
  {
   "type": "setvalue",
   "expression": "{question1} anyof ['item1', 'item2']",
   "setToName": "question.name2",
   "setValue": "one"
  },
  {
   "type": "setvalue",
   "expression": "{question1} anyof ['item3', 'item4']",
   "setToName": "question.name2",
   "setValue": "two"
  }
 ]
}

```

### Specify your

* browser: Chrome
* browser version: 85.0.4183.102
* surveyjs platform (angular or react or jquery or knockout or vue): vue
* survey-vue version: 1.8.5

**Comment by andrewtelnov** [comment]
@dasboe I have fixed the issue by commit above.

Thank you,
Andrew

**Comment by dasboe** [comment]
Great - thanks so much for the quick fix Andrew!
Björn

**Comment by dasboe** [comment]
There is still an issue with dots in triggers. A slightly different example to the above is not working correctly:

```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "dropdown",
     "name": "question.name1",
     "choices": [
      "item1",
      "item2",
      "item3",
      "item4"
     ]
    },
    {
     "type": "text",
     "name": "question.name2"
    }
   ]
  }
 ],
 "triggers": [
  {
   "type": "setvalue",
   "expression": "{question.name1} anyof ['item1', 'item2']",
   "setToName": "question.name2",
   "setValue": "one"
  },
  {
   "type": "setvalue",
   "expression": "{question.name1} anyof ['item3', 'item4']",
   "setToName": "question.name2",
   "setValue": "two"
  }
 ]
}
```

**Comment by andrewtelnov** [comment]
@dasboe I have created [the separate issue](https://github.com/surveyjs/survey-library/issues/2597).

Thank you,
Andrew
