### ISSUE TITLE
Cannot find module 'survey-core' or its corresponding type declarations

### ISSUE THREAD

**Issue by fr3ddy** [surveyjs/survey-library#2775]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
When building the application, we are getting "Cannot find module 'survey-core' or its corresponding type declarations."

### What is the expected behavior?
No errors occur while building the vue app.

### How would you reproduce the current behavior (if this is a bug)?
Get to Version `^1.8.37` and run a build.

### Specify your

* browser: Chrome
* browser version: 89.0.4389.114
* surveyjs platform (angular or react or jquery or knockout or vue): Vue
* surveyjs version: 1.8.37

**Comment by tsv2013** [comment]
I looks like it was fixed here - https://github.com/surveyjs/survey-library/issues/2755

**Comment by tsv2013** [comment]
It looks like it was fixed here - https://github.com/surveyjs/survey-library/issues/2755

**Comment by fr3ddy** [comment]
You are right. Sorry for the duplicate.

**Comment by fr3ddy** [comment]
I did some further investigation, as even with the new version the issue still remains for us.
We found with which set of libraries there is a conflict. I attached an archive with 2 screenshots:
1) If the library call is commented out, everything works fine.
2) We receive an error during connection to library
Also, there is a project in the archive, which consists of 1 component and just calls the library. Also, in "package.json", there is a minimum of other libraries installed and this build causes an error.

[survey-core-error.zip](https://github.com/surveyjs/survey-library/files/6263862/survey-core-error.zip)
Thanks for your support.

**Comment by tsv2013** [comment]
It's a bug indeed. Fix will be available in the nearest minor update.

**Comment by fr3ddy** [comment]
This issue has been fixed, but a new one appeared:
![image](https://user-images.githubusercontent.com/4417241/114882889-b34a9780-9e04-11eb-87b0-a800ad4be7fa.png)
Could you please verify? OR should I create a new bug for that?

**Comment by tsv2013** [comment]
@fr3ddy  fixed

**Comment by esune** [comment]
This is still throwing an error with `survey-vue: 1.8.52`

**Comment by tsv2013** [comment]
@esune fixed via the commit above

**Comment by esune** [comment]
> 
> 
> @esune fixed via the commit above

Thanks! I assume it will be available in `1.8.53` then?

**Comment by tsv2013** [comment]
@esune Sure
