### ISSUE TITLE
Adding panelCount in a nested dynamic panel causes elements to have broken styling

### ISSUE THREAD

**Issue by pelshen** [surveyjs/survey-library#3719]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
When using React, in a nested dynamic panel, adding a panelCount of more than 0 causes the styling to be broken on templateElements in the nested panel. It appears some classes are not added correctly.

### What is the expected behavior?
Styling is the same when you do not add panelCount in a nested dynamic panel.

### How would you reproduce the current behavior (if this is a bug)?
Simply use a nested dynamic panel (a dynamic panel in a dynamic panel, with an element inside it) and then add a panelCount of 1 or more to the inner panel.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/CYBAnZf9xKE3T8dt?preview

Test code (slightly simpler than the plunker, removing superfluous questions)

```
Survey
    .StylesManager
    .applyTheme("modern");

var json = {
 "pages": [
  {
   "name": "Test page",
   "elements": [
    {
     "type": "paneldynamic",
     "name": "panel1",
     "title": "Panel 1",
     "templateElements": [
        {
         "type": "text",
         "name": "testText1",
         "title": "Text 1"
        },
      {
       "type": "paneldynamic",
       "name": "innerPanel1",
       "title": "Inner Panel 1",
       "templateElements": [
        {
         "type": "text",
         "name": "testText2",
         "title": "Text 2"
        }
       ],
       "panelCount": 1,
       "panelAddText": "Add Inner Panel",
       "panelRemoveText": "X"
      }
     ],
     "panelCount": 1,
     "panelAddText": "Add Outer Panel",
     "panelRemoveText": "X"
    }
   ]
  }
 ],
 "showQuestionNumbers": "off",
 "completeText": "Submit"
};

window.survey = new Survey.Model(json);

survey
    .onComplete
    .add(function (sender) {
        document
            .querySelector('#surveyResult')
            .textContent = "Result JSON:\n" + JSON.stringify(sender.data, null, 3);
    });

ReactDOM.render(<Survey.Survey model={survey}/>, document.getElementById("surveyElement"));
```

### Specify your

* browser: Chrome
* browser version: 96
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.9.1

**Comment by andrewtelnov** [comment]
@pelshen We will take a look.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@pelshen I have fixed the issue by the commit above.

Thank you,
Andrew

**Comment by pelshen** [comment]
Sorry, I've tried this by compiling from source and this is much better now, but the sv_row class is still missing on the row div, which breaks the layout if you use `"startWithNewLine": false` as the display: flex is missing.

**Comment by andrewtelnov** [comment]
@pelshen Thank you for testing it. Indeed, css for panel is incorrect as well.
I added several test cases into the unit test and fixed them by the commit above.

Thank you,
Andrew

**Comment by marco-mazzu** [comment]
css is now ok when I add a new panel in dynamicPanel but is still broke when I reload the page
