### ISSUE TITLE
react: text processing not working in html

### ISSUE THREAD

**Issue by masciugo** [surveyjs/survey-library#3761]
### Are you requesting a feature, reporting a bug or asking a question?

bug

### What is the current behavior?

it seems that html question does not apply text processing using other question ref before displaying

https://plnkr.co/edit/QZdMoItJiyln4blN

**Comment by andrewtelnov** [comment]
@masciugo I have added a function test and fixed it by the commit above.

Thank you,
Andrew

**Comment by masciugo** [comment]
Hi
it does not seem fixed with version 1.9.5:

https://plnkr.co/edit/jGuF5gqhMqz2jo83?preview

thank you

**Comment by masciugo** [comment]
Hi @andrewtelnov @dmitrykurmanov sorry if I push you but maybe my last comment was missed. thanks

**Comment by cinziasala** [comment]
Hi, I confirm that also 1.9.6 version the bug still persists
Thank you

**Comment by tsv2013** [comment]
@cinziasala We'll check it

**Comment by andrewtelnov** [comment]
@masciugo There was an error in the example. I have corrected it. Here is the [new link](https://plnkr.co/edit/JpZ5lNzbuP2qzgXx).
It was: "this is name: <span><{name}/span>", instead of: "html": "this is name: <span>{name}</span>"

Thank you,
Andrew

**Comment by masciugo** [comment]
so-sorry. thank you
