### ISSUE TITLE
Trigger changed between 1.12.15 and 1.12.16

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-library#9376]
**Describe the bug**
We have a custom trigger that extends SurveyCompleteTrigger:
```ts
class ScreenoutTrigger extends SurveyTriggerComplete {
	getType() {
		return 'screenouttrigger';
	}

	protected onSuccess(values: HashTable<unknown>, properties: HashTable<unknown>): void {
		console.log('screenoutTrigger', 'onSuccess', this.isRealExecution(), super.isRealExecution(), values, properties);
		if (this.isRealExecution()) {
			this.owner.setTriggerValue('result', 'screenout', false);
			// Parent call
			super.onSuccess(values, properties);
		}
	}
}

serializer.addClass('screenouttrigger', [], () => new ScreenoutTrigger(), 'completetrigger');
```

This is the survey JSON:
```
"pages": [
    {
      "name": "page1",
      "elements": [
        {
          "type": "text",
          "name": "info",
          "title": "Info text"
        },
        {
          "type": "checkbox",
          "name": "question1",
          "isRequired": true,
          "choices": [
            {
              "value": "Item 1",
              "text": "kort"
            },
            {
              "value": "Item 2",
              "text": "middellang",
              "info": "{info}"
            },
          ],
          "showOtherItem": true
        }
      ]
    },
    {
      "name": "page2",
      "elements": [
        {
          "type": "rating",
          "name": "question2",
          "rateType": "smileys"
        }
      ]
    }
  ],
  "triggers": [
    {
      "type": "screenout",
      "expression": "{info} = 'test'"
    }
  ],
  "questionsOnPageMode": "questionPerPage"
}
```

**Steps to reproduce**

1. Enter the text `test` into the first question
2. Click next.

In version 2.11.15 the trigger code is executed twice, once onblur, with `isRealExecution()` `false`. The second time with `true`.
In version 2.11.16 the second execution with `isRealExecution() === true` does not happen when navigation is set to `questionPerPage`.

The changes between 2.11.15 and 2.11.16 are enormous (very nice job btw on the addition of typing) -- but somewhere in those changes is a change of behavior.

**Comment by SamMousa** [comment]
Update, it might have been fixed in .18, I'll keep checking each version. (.21 its broken)

**Comment by andrewtelnov** [comment]
@SamMousa Please let me write the unit test and fix it. I pretty sure the issue is still here. We do not have tests for this case after we stop creating pages for every question on the fly for this mode.

Thank you,
Andrew

**Comment by SamMousa** [comment]
I can repro that too, but there is definitely a change in behavior.
In my case we  subclass the `SurveyCompleteTrigger`:
```ts
import type { HashTable, JsonMetadata } from 'survey-core';

import type { SurveyTriggerComplete as SurveyTriggerCompleteType } from 'survey-core';

export const editorLocalizationStrings = {
	lg: {
		trigger_screenoutName: 'Screenout',
		trigger_screenoutText: 'the response will be marked as a screenout',
		trigger_screenoutDescription: 'Marks the response as a screenout and exits the survey'
	}
};
export default (
	serializer: JsonMetadata,
	SurveyTriggerComplete: typeof SurveyTriggerCompleteType
) => {
	class ScreenoutTrigger extends SurveyTriggerComplete {
		getType() {
			return 'screenouttrigger';
		}

		protected onSuccess(values: HashTable<unknown>, properties: HashTable<unknown>): void {
			console.log('screenoutTrigger', 'onSuccess', this.isRealExecution(), super.isRealExecution());
			if (this.isRealExecution()) {
				this.owner.setTriggerValue('result', 'screenout', false);
				// Parent call
				super.onSuccess(values, properties);
			}
		}
	}

	serializer.addClass('screenouttrigger', [], () => new ScreenoutTrigger(), 'completetrigger');
};
```

Could it be that there is special handling for the `completetrigger`?

**Comment by andrewtelnov** [comment]
@SamMousa Yes, it could be. I will check it out tomorrow. 

Thank you,
Andrew

**Comment by SamMousa** [comment]
https://plnkr.co/edit/4pjv1jWKwrTtKD35

I have updated the plunker, it shows that:
- a custom trigger does not work
- the onTriggerExecuted event does not work

**Comment by SamMousa** [comment]
I've been thinking on this, and maybe the best way forward is not to try and fix everything...
You've introduced a new `performNext()` which goes to the next page / question.
The concept of page has changed.

What we're missing to be able to update our features are ways to hook into the new logic:
1. We need to know when the current single question changes (and what direction this change is)
2. Triggers should probably be checked on each single question change

I'm happy to implement changes to our code if it makes your code cleaner.

**Comment by andrewtelnov** [comment]
@SamMousa Here is [your updated example](https://plnkr.co/edit/vJesffQUkq7XjLYI).
You did not call for all cases.
`
      // Parent call
      super.onSuccess(values, properties);
`

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
I have added the related unit test for your case by [this commit](https://github.com/surveyjs/survey-library/commit/eaaaa438f899de1c34cab080a02a5d37b4b5dfd8).

Thank you,
Andrew

**Comment by SamMousa** [comment]
I'll close this and extract the event based stuff in a new issue.

**Comment by andrewtelnov** [comment]
> I'll close this and extract the event based stuff in a new issue.

We do not call `onPageChanging`/`onPageChanged` will not be called, because we changed the behavior, because we do not create new pages for every questions any more. We render only one question on the same page, one by one.
If needed a new event could be called that tells that the current displayed question is changed.
